"""The root export list is deliberate.

Every name in ``superglm.__all__`` is documented in the API reference and is
what ``from superglm import *`` hands a user, so a change to it is an API
decision: edit this list in the same pull request, where a reviewer sees the
name as a diff line rather than inside a large commit.
"""

from __future__ import annotations

import superglm

PUBLIC_API = [
    "Adaptive",
    "BSplineSmooth",
    "Binomial",
    "Categorical",
    "CauchitLink",
    "CloglogLink",
    "Constraint",
    "CrossValidationResult",
    "CubicRegressionSpline",
    "DiscretizationResult",
    "DispersionTestResult",
    "DoubleLiftChartResult",
    "FactorSmooth",
    "FactorSmoothResult",
    "FitDiagnosticReport",
    "FractionalFrequencyWeightWarning",
    "Gamma",
    "GammaLS",
    "Gaussian",
    "GaussianLS",
    "GeneralizedGammaLSS",
    "GeneralizedParetoLSS",
    "GroupElasticNet",
    "GroupLasso",
    "IdentityLink",
    "InverseLink",
    "InverseSquaredLink",
    "LambdaPolicy",
    "LevelGrouping",
    "LiftChartResult",
    "LogLink",
    "LogNormalLS",
    "LogitLink",
    "LorenzCurveResult",
    "LossRatioChartResult",
    "ModelMetrics",
    "ModelSummary",
    "NBProfileResult",
    "NBThetaBoundWarning",
    "NaturalSpline",
    "NegativeBinomial",
    "NegativeBinomialLS",
    "NegativeBinomialLink",
    "Numeric",
    "OrderedCategorical",
    "PSpline",
    "PathResult",
    "Piecewise",
    "Poisson",
    "Polynomial",
    "PowerLink",
    "Predictor",
    "PriorWeightLatticeWarning",
    "ProbitLink",
    "PublicationModeError",
    "REMLResult",
    "RandomEffect",
    "RandomEffectResult",
    "RatingTableBaseNotRepresentableError",
    "Ridge",
    "ScoreTestZIResult",
    "SeparationError",
    "SeparationWarning",
    "SparseGroupLasso",
    "Spline",
    "SplineRedundancyReport",
    "SqrtLink",
    "SuperGLM",
    "SuperGLMClassifier",
    "SuperGLMRegressor",
    "SuperLSS",
    "TermInference",
    "Tweedie",
    "TweedieLSS",
    "TweedieProfileResult",
    "TwoPieceLogNormalLSS",
    "TwoPieceNormalLSS",
    "VuongTestResult",
    "ZeroInflationResult",
    "bind_predictor",
    "cat",
    "collapse_levels",
    "cross_validate",
    "discretization_impact",
    "dispersion_test",
    "double_lift_chart",
    "estimate_nb_theta",
    "estimate_phi",
    "estimate_tweedie_p",
    "export_rating_tables",
    "families",
    "generate_tweedie_cpg",
    "interaction",
    "lift_chart",
    "lorenz_curve",
    "loss_ratio_chart",
    "n_knots_from_k",
    "plot_term_comparison",
    "psum_chisq",
    "re",
    "s",
    "satterthwaite",
    "score_test_zi",
    "term",
    "ti",
    "tweedie_logpdf",
    "vuong_test",
    "warmup",
    "wood_test_smooth",
    "zero_inflation_index",
]


def test_root_exports_match_the_reviewed_list() -> None:
    assert sorted(superglm.__all__) == PUBLIC_API


def test_reviewed_list_has_no_duplicates_and_is_sorted() -> None:
    assert PUBLIC_API == sorted(set(PUBLIC_API))
