"""Real-data mgcv parity tests on freMTPL2.

Compares SuperGLM against reference values from mgcv::gam() (method="REML")
on prepared subsets of freMTPL2freq and freMTPL2sev.

Tests are organized as:
  - **Parity tests** compare against mgcv reference values with tight
    tolerances (deviance <0.1%, prediction correlation >0.95).
  - **Sanity checks** verify fit() and group-lasso paths converge and
    produce reasonable predictions.  These use wider tolerances because
    they lack REML-estimated smoothing parameters.

Fitting paths tested:
  1. fit_reml(discrete=False) — exact REML       [parity]
  2. fit_reml(discrete=True)  — fREML, 256 bins  [parity vs exact]
  3. fit(selection_penalty=0)           — direct IRLS       [sanity]
  4. fit(lambda1>0)           — group lasso BCD   [sanity]

Data:
  Uses tests/_datasets.py to locate freMTPL2 parquet files (checks
  $SUPERGLM_DATA_DIR, ~/.cache/superglm/, and <project>/data/ in order).
  All tests skip when data is absent, so CI is unaffected.  No derived
  data blobs are committed.

  NB2: deterministic 50k subsample (sorted by IDpol, first 50k)
  Gamma: all claims joined with freq features (~25k rows)

Reference values (hardcoded below):
  Generated by scratch/r_experiments/realdata_parity_reference.R
  R 4.5.2, mgcv 1.9-3, bs="cr" (cubic regression spline)

Basis alignment:
  mgcv bs="cr" with k=K gives K-1 free basis columns after absorbing the
  identifiability constraint.  SuperGLM Spline(kind="cr", k=K) produces
  K-1 built columns (identifiability direction physically removed).
  The integrated-f'' penalty matches mgcv's default m=2 for cr.
"""

import numpy as np
import pytest

from superglm import SuperGLM
from superglm.distributions import NegativeBinomial
from superglm.features.categorical import Categorical
from superglm.features.spline import Spline

from . import _datasets

# ── mgcv reference values ────────────────────────────────────────────
# R 4.5.2, mgcv 1.9-3, bs="cr", method="REML"

MGCV_NB2 = {
    # mgcv nb() with outer theta estimation.  theta=17541 means
    # near-Poisson (V(mu) ≈ mu).  At large theta, NB2 deviance
    # converges to Poisson deviance.
    "theta": 17541.2,
    "deviance": 39679.83,
    "edf_smooth": {"DrivAge": 7.00, "VehAge": 8.89, "BonusMalus": 6.91},
    "edf_total": 28.80,
    "intercept": -0.9837,
    "pred_mean": 0.5341,
    "pred_cor_y": 0.382,
}

MGCV_GAMMA = {
    "deviance": 39083.21,
    # mgcv "scale" is Pearson-based: sum((y-mu)^2/V(mu)) / (n-edf).
    # This differs from deviance-based phi = deviance/(n-edf).
    # For Gamma, deviance phi ≈ 1.57 while Pearson phi ≈ 22.47.
    "pearson_scale": 22.47,
    "edf_smooth": {"DrivAge": 13.63, "VehAge": 8.63, "BonusMalus": 8.62},
    "edf_total": 36.88,
    "intercept": 7.792,
    "pred_mean": 2333.6,
}

# NB2 with theta=1000 is near-Poisson on this data, so predictions
# should match mgcv closely.  NB2 deviance uses a theta-dependent
# formula, so we compare predictions and EDF rather than deviance.
NB2_THETA = 1000


def _freq_available():
    return _datasets.find("freMTPL2freq.parquet") is not None


def _sev_available():
    return _datasets.find("freMTPL2sev.parquet") is not None


def _prep_freq(df):
    """Standard freMTPL2freq preparation (must match R script exactly)."""
    df = df.copy()
    df["ClaimNb"] = df["ClaimNb"].clip(upper=4)
    df["Exposure"] = df["Exposure"].clip(lower=0.01)
    df["DrivAge"] = df["DrivAge"].clip(18, 90)
    df["VehAge"] = df["VehAge"].clip(0, 20)
    df["BonusMalus"] = df["BonusMalus"].clip(50, 150)
    return df


def _load_nb2_data():
    """Load 50k NB2 subsample: sort by IDpol, take first 50k."""
    df = _datasets.load_freq()
    df = _prep_freq(df)
    df = df.sort_values("IDpol").reset_index(drop=True).iloc[:50000]
    y = df["ClaimNb"].values.astype(float)
    offset = np.log(df["Exposure"].values)
    return df, y, offset


def _load_gamma_data():
    """Load Gamma severity: join freq features with aggregated claims."""
    freq = _datasets.load_freq()
    freq = _prep_freq(freq)
    sev = _datasets.load_sev()
    sev_agg = sev.groupby("IDpol")["ClaimAmount"].sum().reset_index()
    merged = freq.merge(sev_agg, on="IDpol", how="inner")
    y = merged["ClaimAmount"].values.astype(float)
    return merged, y


def _features(discrete=False):
    return {
        "DrivAge": Spline(kind="cr", k=15, discrete=discrete),
        "VehAge": Spline(kind="cr", k=10, discrete=discrete),
        "BonusMalus": Spline(kind="cr", k=10, discrete=discrete),
        "Area": Categorical(),
    }


# ═══════════════════════════════════════════════════════════════════════
# NB2 parity — freMTPL2freq (50k subsample)
#
# mgcv estimates theta=17541 (near-Poisson).  We use NB2 with
# theta=1000 which exercises the full NB2 fit path while producing
# predictions nearly identical to Poisson.  NB2 deviance formula
# differs from Poisson (depends on theta), so parity is measured
# via predictions and EDF, not deviance.
# ═══════════════════════════════════════════════════════════════════════

NB2_SKIP = pytest.mark.skipif(
    not _freq_available(),
    reason="data/freMTPL2freq.parquet not found (gitignored)",
)


@NB2_SKIP
class TestNB2ExactREML:
    """NB2 fit_reml(discrete=False) — parity vs mgcv."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y, offset = _load_nb2_data()
        m = SuperGLM(
            features=_features(),
            family=NegativeBinomial(theta=NB2_THETA),
            selection_penalty=0,
        )
        m.fit_reml(df, y, offset=offset, max_reml_iter=30)
        return m, df, y, offset

    def test_convergence(self, model):
        m, *_ = model
        assert m._reml_result.converged

    def test_edf_total(self, model):
        """Total EDF within ±2 of mgcv."""
        m, *_ = model
        diff = abs(m.result.effective_df - MGCV_NB2["edf_total"])
        assert diff < 2.0, (
            f"EDF {m.result.effective_df:.1f} vs mgcv {MGCV_NB2['edf_total']:.1f} (diff {diff:.1f})"
        )

    def test_prediction_mean(self, model):
        """Mean prediction within 5% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)
        rel = abs(mu.mean() - MGCV_NB2["pred_mean"]) / MGCV_NB2["pred_mean"]
        assert rel < 0.05, (
            f"pred_mean {mu.mean():.4f} vs mgcv {MGCV_NB2['pred_mean']:.4f} (rel diff {rel:.4f})"
        )

    def test_prediction_correlation_with_y(self, model):
        m, df, y, *_ = model
        mu = m.predict(df)
        r = np.corrcoef(y, mu)[0, 1]
        assert r > 0.30, f"pred-response correlation {r:.3f} too low"


@NB2_SKIP
class TestNB2DiscreteREML:
    """NB2 fit_reml(discrete=True) — parity vs exact REML."""

    @pytest.fixture(scope="class")
    def models(self):
        df, y, offset = _load_nb2_data()
        m_exact = SuperGLM(
            features=_features(),
            family=NegativeBinomial(theta=NB2_THETA),
            selection_penalty=0,
        )
        m_exact.fit_reml(df, y, offset=offset, max_reml_iter=30)
        m_disc = SuperGLM(
            features=_features(discrete=True),
            family=NegativeBinomial(theta=NB2_THETA),
            selection_penalty=0,
            discrete=True,
            n_bins=256,
        )
        m_disc.fit_reml(df, y, offset=offset, max_reml_iter=30)
        return m_exact, m_disc, df, y

    def test_convergence(self, models):
        _, m_disc, *_ = models
        assert m_disc._reml_result.converged

    def test_edf_vs_exact(self, models):
        """Discrete EDF within ±2 of exact REML."""
        m_exact, m_disc, *_ = models
        diff = abs(m_disc.result.effective_df - m_exact.result.effective_df)
        assert diff < 2.0, (
            f"Discrete EDF {m_disc.result.effective_df:.1f} vs "
            f"exact {m_exact.result.effective_df:.1f} (diff {diff:.1f})"
        )

    def test_prediction_correlation(self, models):
        """Discrete predictions should correlate >0.999 with exact."""
        m_exact, m_disc, df, *_ = models
        mu_exact = m_exact.predict(df)
        mu_disc = m_disc.predict(df)
        r = np.corrcoef(mu_exact, mu_disc)[0, 1]
        assert r > 0.999, f"exact-discrete pred corr {r:.6f}"


@NB2_SKIP
class TestNB2ThetaEstimation:
    """NB2 theta estimation via MASS-style alternating."""

    def test_theta_near_poisson(self):
        """mgcv gets theta=17541.  Our estimator should find theta > 100."""
        df, y, offset = _load_nb2_data()
        m = SuperGLM(
            features=_features(),
            family=NegativeBinomial(theta=1.0),
            selection_penalty=0,
        )
        result = m.estimate_theta(df, y, offset=offset, theta_bounds=(0.1, 100000))
        assert result.theta_hat > 100, f"Theta {result.theta_hat:.1f} should be >100 (near-Poisson)"


# ── NB2 sanity checks (wider tolerances, no REML) ────────────────────


@NB2_SKIP
class TestNB2DirectFitSanity:
    """NB2 fit(selection_penalty=0) — convergence and rough prediction check."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y, offset = _load_nb2_data()
        m = SuperGLM(
            features=_features(),
            family=NegativeBinomial(theta=NB2_THETA),
            selection_penalty=0,
            spline_penalty=1.0,
        )
        m.fit(df, y, offset=offset)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_mean(self, model):
        """Mean prediction within 10% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        rel = abs(mu.mean() - MGCV_NB2["pred_mean"]) / MGCV_NB2["pred_mean"]
        assert rel < 0.10, f"pred_mean {mu.mean():.4f} vs mgcv {MGCV_NB2['pred_mean']:.4f}"


@NB2_SKIP
class TestNB2GroupLassoSanity:
    """NB2 fit(lambda1>0) — convergence and rough prediction check."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y, offset = _load_nb2_data()
        m = SuperGLM(
            features=_features(),
            family=NegativeBinomial(theta=NB2_THETA),
            penalty="group_lasso",
            selection_penalty=0.001,
        )
        m.fit(df, y, offset=offset)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_correlation_with_y(self, model):
        m, df, y, *_ = model
        mu = m.predict(df)
        r = np.corrcoef(y, mu)[0, 1]
        assert r > 0.20, f"pred-response correlation {r:.3f} too low"


# ═══════════════════════════════════════════════════════════════════════
# Gamma parity — freMTPL2sev (~25k policies with claims)
# ═══════════════════════════════════════════════════════════════════════

GAMMA_SKIP = pytest.mark.skipif(
    not _sev_available(),
    reason="data/freMTPL2sev.parquet not found (gitignored)",
)


@GAMMA_SKIP
class TestGammaExactREML:
    """Gamma fit_reml(discrete=False) — parity vs mgcv."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y = _load_gamma_data()
        m = SuperGLM(features=_features(), family="gamma", selection_penalty=0)
        m.fit_reml(df, y, max_reml_iter=30)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m._reml_result.converged

    def test_deviance(self, model):
        """Deviance within 0.1% of mgcv."""
        m, *_ = model
        rel = abs(m.result.deviance - MGCV_GAMMA["deviance"]) / MGCV_GAMMA["deviance"]
        assert rel < 0.001, (
            f"Deviance {m.result.deviance:.1f} vs mgcv {MGCV_GAMMA['deviance']:.1f} "
            f"(rel diff {rel:.5f})"
        )

    def test_edf_total(self, model):
        """Total EDF within ±2 of mgcv."""
        m, *_ = model
        diff = abs(m.result.effective_df - MGCV_GAMMA["edf_total"])
        assert diff < 2.0, (
            f"EDF {m.result.effective_df:.1f} vs mgcv {MGCV_GAMMA['edf_total']:.1f} "
            f"(diff {diff:.1f})"
        )

    def test_pearson_scale(self, model):
        """Pearson scale within 10% of mgcv.

        mgcv reports Pearson-based scale: sum((y-mu)^2/V(mu)) / (n-edf).
        SuperGLM's result.phi is deviance-based.  We compute Pearson phi
        manually for comparison.
        """
        m, df, y = model
        mu = m.predict(df)
        pearson_chi2 = float(np.sum((y - mu) ** 2 / mu**2))
        pearson_phi = pearson_chi2 / (len(y) - m.result.effective_df)
        rel = abs(pearson_phi - MGCV_GAMMA["pearson_scale"]) / MGCV_GAMMA["pearson_scale"]
        assert rel < 0.10, (
            f"Pearson phi {pearson_phi:.2f} vs mgcv {MGCV_GAMMA['pearson_scale']:.2f} "
            f"(rel diff {rel:.4f})"
        )

    def test_prediction_mean(self, model):
        """Mean prediction within 5% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)
        rel = abs(mu.mean() - MGCV_GAMMA["pred_mean"]) / MGCV_GAMMA["pred_mean"]
        assert rel < 0.05, (
            f"pred_mean {mu.mean():.1f} vs mgcv {MGCV_GAMMA['pred_mean']:.1f} (rel diff {rel:.4f})"
        )


@GAMMA_SKIP
class TestGammaDiscreteREML:
    """Gamma fit_reml(discrete=True) — parity vs exact REML."""

    @pytest.fixture(scope="class")
    def models(self):
        df, y = _load_gamma_data()
        m_exact = SuperGLM(features=_features(), family="gamma", selection_penalty=0)
        m_exact.fit_reml(df, y, max_reml_iter=30)
        m_disc = SuperGLM(
            features=_features(discrete=True),
            family="gamma",
            selection_penalty=0,
            discrete=True,
            n_bins=256,
        )
        m_disc.fit_reml(df, y, max_reml_iter=30)
        return m_exact, m_disc, df, y

    def test_convergence(self, models):
        _, m_disc, *_ = models
        assert m_disc._reml_result.converged

    def test_deviance_vs_exact(self, models):
        """Discrete deviance within 0.5% of exact REML."""
        m_exact, m_disc, *_ = models
        rel = abs(m_disc.result.deviance - m_exact.result.deviance) / m_exact.result.deviance
        assert rel < 0.005, (
            f"Discrete dev {m_disc.result.deviance:.1f} vs "
            f"exact {m_exact.result.deviance:.1f} (rel diff {rel:.5f})"
        )

    def test_edf_vs_exact(self, models):
        """Discrete EDF within ±2 of exact REML."""
        m_exact, m_disc, *_ = models
        diff = abs(m_disc.result.effective_df - m_exact.result.effective_df)
        assert diff < 2.0, (
            f"Discrete EDF {m_disc.result.effective_df:.1f} vs "
            f"exact {m_exact.result.effective_df:.1f} (diff {diff:.1f})"
        )

    def test_prediction_correlation(self, models):
        """Discrete predictions should correlate >0.999 with exact."""
        m_exact, m_disc, df, *_ = models
        mu_exact = m_exact.predict(df)
        mu_disc = m_disc.predict(df)
        r = np.corrcoef(mu_exact, mu_disc)[0, 1]
        assert r > 0.999, f"exact-discrete pred corr {r:.6f}"


# ── Gamma sanity checks (wider tolerances, no REML) ──────────────────


@GAMMA_SKIP
class TestGammaDirectFitSanity:
    """Gamma fit(selection_penalty=0) — convergence and rough prediction check."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y = _load_gamma_data()
        m = SuperGLM(features=_features(), family="gamma", selection_penalty=0, spline_penalty=1.0)
        m.fit(df, y)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_mean(self, model):
        """Mean prediction within 10% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        rel = abs(mu.mean() - MGCV_GAMMA["pred_mean"]) / MGCV_GAMMA["pred_mean"]
        assert rel < 0.10, f"pred_mean {mu.mean():.1f} vs mgcv {MGCV_GAMMA['pred_mean']:.1f}"


@GAMMA_SKIP
class TestGammaGroupLassoSanity:
    """Gamma fit(lambda1>0) — convergence and rough prediction check."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y = _load_gamma_data()
        m = SuperGLM(
            features=_features(),
            family="gamma",
            penalty="group_lasso",
            selection_penalty=0.001,
        )
        m.fit(df, y)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_correlation_with_y(self, model):
        m, df, y, *_ = model
        mu = m.predict(df)
        r = np.corrcoef(y, mu)[0, 1]
        # Severity prediction is inherently weak
        assert r > 0.01, f"pred-response correlation {r:.3f} too low"
