"""Real-data mgcv parity tests on freMTPL2.

Compares SuperGLM across all fitting paths against reference values from
mgcv::gam() (method="REML") on prepared subsets of freMTPL2freq/sev.

Fitting paths tested:
  1. fit_reml(discrete=False) — exact REML (primary mgcv comparison)
  2. fit_reml(discrete=True)  — fREML with binned basis
  3. fit(lambda1=0)           — direct IRLS, no REML
  4. fit(lambda1>0)           — group lasso + PIRLS BCD

Reference values generated by:
  scratch/r_experiments/realdata_parity_reference.R
  R 4.5.2, mgcv 1.9-3, bs="cr" (cubic regression spline)

Fixture data (committed as .csv.gz, CI-runnable):
  tests/fixtures/mtpl2_freq_50k.csv.gz   — 50k-row subset, sorted by IDpol
  tests/fixtures/mtpl2_sev_merged.csv.gz — freq+sev joined (~25k rows)
  Generated by scratch/export_parity_fixtures.py.

  mgcv fitted values (optional, for prediction comparison):
  tests/fixtures/mgcv_nb2_mtpl2_fitted.csv.gz
  tests/fixtures/mgcv_gamma_mtpl2sev_fitted.csv.gz
  Generated by scratch/r_experiments/realdata_parity_reference.R.
  Tests skip gracefully if these are absent.

Basis alignment:
  mgcv bs="cr" with k=K gives K-1 free basis columns after absorbing the
  identifiability constraint.  SuperGLM Spline(kind="cr", k=K) produces
  K-1 built columns (identifiability direction physically removed).
  The integrated-f'' penalty matches mgcv's default m=2 for cr.
"""

import os

import numpy as np
import pandas as pd
import pytest

from superglm import SuperGLM
from superglm.features.categorical import Categorical
from superglm.features.spline import Spline

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")

# ── mgcv reference values ────────────────────────────────────────────
# R 4.5.2, mgcv 1.9-3, bs="cr", method="REML"

MGCV_NB2 = {
    # mgcv nb() with outer theta estimation.  theta=17541 means
    # near-Poisson (V(mu) ≈ mu).  At large theta, NB2 deviance
    # converges to Poisson deviance.
    "theta": 17541.2,
    "deviance": 39679.83,
    "edf_smooth": {"DrivAge": 7.00, "VehAge": 8.89, "BonusMalus": 6.91},
    "edf_total": 28.80,
    "intercept": -0.9837,
    "pred_mean": 0.5341,
    "pred_cor_y": 0.382,
}

MGCV_GAMMA = {
    "deviance": 39083.21,
    # mgcv "scale" is Pearson-based: sum((y-mu)^2/V(mu)) / (n-edf).
    # This differs from deviance-based phi = deviance/(n-edf).
    # For Gamma, deviance phi ≈ 1.57 while Pearson phi ≈ 22.47.
    "pearson_scale": 22.47,
    "edf_smooth": {"DrivAge": 13.63, "VehAge": 8.63, "BonusMalus": 8.62},
    "edf_total": 36.88,
    "intercept": 7.792,
    "pred_mean": 2333.6,
}


def _nb2_data_available():
    return os.path.exists(os.path.join(FIXTURES, "mtpl2_freq_50k.csv.gz"))


def _gamma_data_available():
    return os.path.exists(os.path.join(FIXTURES, "mtpl2_sev_merged.csv.gz"))


def _load_nb2_data():
    """Load prepared 50k NB2 subsample from committed fixture."""
    df = pd.read_csv(os.path.join(FIXTURES, "mtpl2_freq_50k.csv.gz"))
    y = df["ClaimNb"].values.astype(float)
    offset = np.log(df["Exposure"].values)
    return df, y, offset


def _load_gamma_data():
    """Load prepared Gamma severity data from committed fixture."""
    df = pd.read_csv(os.path.join(FIXTURES, "mtpl2_sev_merged.csv.gz"))
    y = df["ClaimAmount"].values.astype(float)
    return df, y


def _features(discrete=False):
    return {
        "DrivAge": Spline(kind="cr", k=15, discrete=discrete),
        "VehAge": Spline(kind="cr", k=10, discrete=discrete),
        "BonusMalus": Spline(kind="cr", k=10, discrete=discrete),
        "Area": Categorical(),
    }


# ═══════════════════════════════════════════════════════════════════════
# NB2 / Poisson parity
# ═══════════════════════════════════════════════════════════════════════

NB2_SKIP = pytest.mark.skipif(
    not _nb2_data_available(),
    reason="tests/fixtures/mtpl2_freq_50k.csv.gz not found",
)


@NB2_SKIP
class TestNB2ExactREML:
    """Poisson fit_reml(discrete=False) vs mgcv nb() — primary comparison.

    mgcv estimates theta=17541 — near-Poisson.  Since NB2 → Poisson as
    theta → ∞, we fit Poisson with exact REML (deviance and EDF match
    mgcv NB2 to <0.1%).
    """

    @pytest.fixture(scope="class")
    def model(self):
        df, y, offset = _load_nb2_data()
        m = SuperGLM(features=_features(), family="poisson", lambda1=0)
        m.fit_reml(df, y, offset=offset, max_reml_iter=30)
        return m, df, y, offset

    def test_convergence(self, model):
        m, *_ = model
        assert m._reml_result.converged

    def test_deviance(self, model):
        """Deviance within 0.1% of mgcv."""
        m, *_ = model
        rel = abs(m.result.deviance - MGCV_NB2["deviance"]) / MGCV_NB2["deviance"]
        assert rel < 0.001, (
            f"Deviance {m.result.deviance:.1f} vs mgcv {MGCV_NB2['deviance']:.1f} "
            f"(rel diff {rel:.5f})"
        )

    def test_edf_total(self, model):
        """Total EDF within ±2 of mgcv."""
        m, *_ = model
        diff = abs(m.result.effective_df - MGCV_NB2["edf_total"])
        assert diff < 2.0, (
            f"EDF {m.result.effective_df:.1f} vs mgcv {MGCV_NB2['edf_total']:.1f} (diff {diff:.1f})"
        )

    def test_prediction_mean(self, model):
        """Mean prediction within 5% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)
        rel = abs(mu.mean() - MGCV_NB2["pred_mean"]) / MGCV_NB2["pred_mean"]
        assert rel < 0.05, (
            f"pred_mean {mu.mean():.4f} vs mgcv {MGCV_NB2['pred_mean']:.4f} (rel diff {rel:.4f})"
        )

    def test_prediction_correlation_with_y(self, model):
        m, df, y, *_ = model
        mu = m.predict(df)
        r = np.corrcoef(y, mu)[0, 1]
        assert r > 0.30, f"pred-response correlation {r:.3f} too low"

    def test_prediction_vs_mgcv_fitted(self, model):
        """Predictions should correlate highly with mgcv fitted values."""
        m, df, *_ = model
        fitted_path = os.path.join(FIXTURES, "mgcv_nb2_mtpl2_fitted.csv.gz")
        if not os.path.exists(fitted_path):
            pytest.skip("mgcv fitted values not exported")
        mgcv_fitted = pd.read_csv(fitted_path)
        mu = m.predict(df)
        r = np.corrcoef(mu, mgcv_fitted["fitted"].values)[0, 1]
        assert r > 0.95, f"SuperGLM-mgcv pred corr {r:.4f}"


@NB2_SKIP
class TestNB2DiscreteREML:
    """Poisson fit_reml(discrete=True) — fREML with binned basis.

    Compared against exact REML (not mgcv directly).  Discretization
    should produce nearly identical results on 50k rows with 256 bins.
    """

    @pytest.fixture(scope="class")
    def models(self):
        df, y, offset = _load_nb2_data()
        # Exact REML baseline
        m_exact = SuperGLM(features=_features(), family="poisson", lambda1=0)
        m_exact.fit_reml(df, y, offset=offset, max_reml_iter=30)
        # Discrete fREML
        m_disc = SuperGLM(
            features=_features(discrete=True),
            family="poisson",
            lambda1=0,
            discrete=True,
            n_bins=256,
        )
        m_disc.fit_reml(df, y, offset=offset, max_reml_iter=30)
        return m_exact, m_disc, df, y

    def test_convergence(self, models):
        _, m_disc, *_ = models
        assert m_disc._reml_result.converged

    def test_deviance_vs_exact(self, models):
        """Discrete deviance within 0.5% of exact REML."""
        m_exact, m_disc, *_ = models
        rel = abs(m_disc.result.deviance - m_exact.result.deviance) / m_exact.result.deviance
        assert rel < 0.005, (
            f"Discrete dev {m_disc.result.deviance:.1f} vs exact {m_exact.result.deviance:.1f} "
            f"(rel diff {rel:.5f})"
        )

    def test_edf_vs_exact(self, models):
        """Discrete EDF within ±2 of exact REML."""
        m_exact, m_disc, *_ = models
        diff = abs(m_disc.result.effective_df - m_exact.result.effective_df)
        assert diff < 2.0, (
            f"Discrete EDF {m_disc.result.effective_df:.1f} vs exact {m_exact.result.effective_df:.1f} "
            f"(diff {diff:.1f})"
        )

    def test_prediction_correlation(self, models):
        """Discrete predictions should correlate >0.999 with exact."""
        m_exact, m_disc, df, *_ = models
        mu_exact = m_exact.predict(df)
        mu_disc = m_disc.predict(df)
        r = np.corrcoef(mu_exact, mu_disc)[0, 1]
        assert r > 0.999, f"exact-discrete pred corr {r:.6f}"


@NB2_SKIP
class TestNB2DirectFit:
    """Poisson fit(lambda1=0) — direct IRLS, no REML.

    Without REML, smoothing lambdas are fixed at defaults.  Deviance
    should still be in the right ballpark (within 5% of mgcv) and
    predictions should be reasonable.
    """

    @pytest.fixture(scope="class")
    def model(self):
        df, y, offset = _load_nb2_data()
        m = SuperGLM(features=_features(), family="poisson", lambda1=0, lambda2=1.0)
        m.fit(df, y, offset=offset)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_deviance_reasonable(self, model):
        """Deviance within 5% of mgcv (no REML, so wider tolerance)."""
        m, *_ = model
        rel = abs(m.result.deviance - MGCV_NB2["deviance"]) / MGCV_NB2["deviance"]
        assert rel < 0.05, (
            f"Deviance {m.result.deviance:.1f} vs mgcv {MGCV_NB2['deviance']:.1f} "
            f"(rel diff {rel:.4f})"
        )

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_mean(self, model):
        """Mean prediction within 10% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        rel = abs(mu.mean() - MGCV_NB2["pred_mean"]) / MGCV_NB2["pred_mean"]
        assert rel < 0.10, f"pred_mean {mu.mean():.4f} vs mgcv {MGCV_NB2['pred_mean']:.4f}"


@NB2_SKIP
class TestNB2GroupLasso:
    """Poisson fit(lambda1>0) — group lasso + PIRLS BCD.

    With penalty active, deviance will be higher than unpenalised.
    Test that the fit converges and produces sensible predictions.
    """

    @pytest.fixture(scope="class")
    def model(self):
        df, y, offset = _load_nb2_data()
        m = SuperGLM(
            features=_features(),
            family="poisson",
            penalty="group_lasso",
            lambda1=0.001,
        )
        m.fit(df, y, offset=offset)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_deviance_not_much_worse(self, model):
        """Penalised deviance within 10% of mgcv unpenalised."""
        m, *_ = model
        rel = abs(m.result.deviance - MGCV_NB2["deviance"]) / MGCV_NB2["deviance"]
        assert rel < 0.10, (
            f"Deviance {m.result.deviance:.1f} vs mgcv {MGCV_NB2['deviance']:.1f} "
            f"(rel diff {rel:.4f})"
        )

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_correlation_with_y(self, model):
        m, df, y, *_ = model
        mu = m.predict(df)
        r = np.corrcoef(y, mu)[0, 1]
        assert r > 0.20, f"pred-response correlation {r:.3f} too low"


@NB2_SKIP
class TestNB2ThetaEstimation:
    """NB2 theta estimation on freMTPL2freq."""

    def test_theta_near_poisson(self):
        """mgcv gets theta=17541.  Our estimator should find theta > 100."""
        from superglm.distributions import NegativeBinomial

        df, y, offset = _load_nb2_data()
        m = SuperGLM(
            features=_features(),
            family=NegativeBinomial(theta=1.0),
            lambda1=0,
        )
        result = m.estimate_theta(df, y, offset=offset, theta_bounds=(0.1, 100000))
        assert result.theta_hat > 100, f"Theta {result.theta_hat:.1f} should be >100 (near-Poisson)"


# ═══════════════════════════════════════════════════════════════════════
# Gamma severity parity
# ═══════════════════════════════════════════════════════════════════════

GAMMA_SKIP = pytest.mark.skipif(
    not _gamma_data_available(),
    reason="tests/fixtures/mtpl2_sev_merged.csv.gz not found",
)


@GAMMA_SKIP
class TestGammaExactREML:
    """Gamma fit_reml(discrete=False) vs mgcv — primary comparison."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y = _load_gamma_data()
        m = SuperGLM(features=_features(), family="gamma", lambda1=0)
        m.fit_reml(df, y, max_reml_iter=30)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m._reml_result.converged

    def test_deviance(self, model):
        """Deviance within 0.1% of mgcv."""
        m, *_ = model
        rel = abs(m.result.deviance - MGCV_GAMMA["deviance"]) / MGCV_GAMMA["deviance"]
        assert rel < 0.001, (
            f"Deviance {m.result.deviance:.1f} vs mgcv {MGCV_GAMMA['deviance']:.1f} "
            f"(rel diff {rel:.5f})"
        )

    def test_edf_total(self, model):
        """Total EDF within ±2 of mgcv."""
        m, *_ = model
        diff = abs(m.result.effective_df - MGCV_GAMMA["edf_total"])
        assert diff < 2.0, (
            f"EDF {m.result.effective_df:.1f} vs mgcv {MGCV_GAMMA['edf_total']:.1f} "
            f"(diff {diff:.1f})"
        )

    def test_pearson_scale(self, model):
        """Pearson scale within 10% of mgcv.

        mgcv reports Pearson-based scale: sum((y-mu)^2/V(mu)) / (n-edf).
        SuperGLM's result.phi is deviance-based.  We compute Pearson phi
        manually for comparison.
        """
        m, df, y = model
        mu = m.predict(df)
        pearson_chi2 = float(np.sum((y - mu) ** 2 / mu**2))
        pearson_phi = pearson_chi2 / (len(y) - m.result.effective_df)
        rel = abs(pearson_phi - MGCV_GAMMA["pearson_scale"]) / MGCV_GAMMA["pearson_scale"]
        assert rel < 0.10, (
            f"Pearson phi {pearson_phi:.2f} vs mgcv {MGCV_GAMMA['pearson_scale']:.2f} "
            f"(rel diff {rel:.4f})"
        )

    def test_prediction_mean(self, model):
        """Mean prediction within 5% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)
        rel = abs(mu.mean() - MGCV_GAMMA["pred_mean"]) / MGCV_GAMMA["pred_mean"]
        assert rel < 0.05, (
            f"pred_mean {mu.mean():.1f} vs mgcv {MGCV_GAMMA['pred_mean']:.1f} (rel diff {rel:.4f})"
        )

    def test_prediction_vs_mgcv_fitted(self, model):
        """Predictions should correlate highly with mgcv fitted values."""
        m, df, *_ = model
        fitted_path = os.path.join(FIXTURES, "mgcv_gamma_mtpl2sev_fitted.csv.gz")
        if not os.path.exists(fitted_path):
            pytest.skip("mgcv fitted values not exported")
        mgcv_fitted = pd.read_csv(fitted_path)
        mu = m.predict(df)
        r = np.corrcoef(mu, mgcv_fitted["fitted"].values)[0, 1]
        assert r > 0.95, f"SuperGLM-mgcv pred corr {r:.4f}"


@GAMMA_SKIP
class TestGammaDiscreteREML:
    """Gamma fit_reml(discrete=True) — fREML with binned basis.

    Compared against exact REML.
    """

    @pytest.fixture(scope="class")
    def models(self):
        df, y = _load_gamma_data()
        m_exact = SuperGLM(features=_features(), family="gamma", lambda1=0)
        m_exact.fit_reml(df, y, max_reml_iter=30)
        m_disc = SuperGLM(
            features=_features(discrete=True),
            family="gamma",
            lambda1=0,
            discrete=True,
            n_bins=256,
        )
        m_disc.fit_reml(df, y, max_reml_iter=30)
        return m_exact, m_disc, df, y

    def test_convergence(self, models):
        _, m_disc, *_ = models
        assert m_disc._reml_result.converged

    def test_deviance_vs_exact(self, models):
        """Discrete deviance within 0.5% of exact REML."""
        m_exact, m_disc, *_ = models
        rel = abs(m_disc.result.deviance - m_exact.result.deviance) / m_exact.result.deviance
        assert rel < 0.005, (
            f"Discrete dev {m_disc.result.deviance:.1f} vs exact {m_exact.result.deviance:.1f} "
            f"(rel diff {rel:.5f})"
        )

    def test_edf_vs_exact(self, models):
        """Discrete EDF within ±2 of exact REML."""
        m_exact, m_disc, *_ = models
        diff = abs(m_disc.result.effective_df - m_exact.result.effective_df)
        assert diff < 2.0, (
            f"Discrete EDF {m_disc.result.effective_df:.1f} vs exact {m_exact.result.effective_df:.1f} "
            f"(diff {diff:.1f})"
        )

    def test_prediction_correlation(self, models):
        """Discrete predictions should correlate >0.999 with exact."""
        m_exact, m_disc, df, *_ = models
        mu_exact = m_exact.predict(df)
        mu_disc = m_disc.predict(df)
        r = np.corrcoef(mu_exact, mu_disc)[0, 1]
        assert r > 0.999, f"exact-discrete pred corr {r:.6f}"


@GAMMA_SKIP
class TestGammaDirectFit:
    """Gamma fit(lambda1=0) — direct IRLS, no REML."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y = _load_gamma_data()
        m = SuperGLM(features=_features(), family="gamma", lambda1=0, lambda2=1.0)
        m.fit(df, y)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_deviance_reasonable(self, model):
        """Deviance within 5% of mgcv (no REML, so wider tolerance)."""
        m, *_ = model
        rel = abs(m.result.deviance - MGCV_GAMMA["deviance"]) / MGCV_GAMMA["deviance"]
        assert rel < 0.05, (
            f"Deviance {m.result.deviance:.1f} vs mgcv {MGCV_GAMMA['deviance']:.1f} "
            f"(rel diff {rel:.4f})"
        )

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_mean(self, model):
        """Mean prediction within 10% of mgcv."""
        m, df, *_ = model
        mu = m.predict(df)
        rel = abs(mu.mean() - MGCV_GAMMA["pred_mean"]) / MGCV_GAMMA["pred_mean"]
        assert rel < 0.10, f"pred_mean {mu.mean():.1f} vs mgcv {MGCV_GAMMA['pred_mean']:.1f}"


@GAMMA_SKIP
class TestGammaGroupLasso:
    """Gamma fit(lambda1>0) — group lasso + PIRLS BCD."""

    @pytest.fixture(scope="class")
    def model(self):
        df, y = _load_gamma_data()
        m = SuperGLM(
            features=_features(),
            family="gamma",
            penalty="group_lasso",
            lambda1=0.001,
        )
        m.fit(df, y)
        return m, df, y

    def test_convergence(self, model):
        m, *_ = model
        assert m.result.converged

    def test_deviance_not_much_worse(self, model):
        """Penalised deviance within 10% of mgcv unpenalised."""
        m, *_ = model
        rel = abs(m.result.deviance - MGCV_GAMMA["deviance"]) / MGCV_GAMMA["deviance"]
        assert rel < 0.10, (
            f"Deviance {m.result.deviance:.1f} vs mgcv {MGCV_GAMMA['deviance']:.1f} "
            f"(rel diff {rel:.4f})"
        )

    def test_predictions_positive(self, model):
        m, df, *_ = model
        mu = m.predict(df)
        assert np.all(mu > 0)

    def test_prediction_correlation_with_y(self, model):
        m, df, y, *_ = model
        mu = m.predict(df)
        r = np.corrcoef(y, mu)[0, 1]
        # Severity prediction is inherently weak
        assert r > 0.01, f"pred-response correlation {r:.3f} too low"
