import Mathlib

/-!
# Nested random-effect elimination: exact finite-dimensional contracts

These statements concern finite matrices over the real numbers.  They are the
algebraic contracts behind the nested-chain elimination proposed in
`notes/research/2026-09-26-nested-random-effect-elimination.md`.

What is proved:

1. `det_bordered_schur`: `det [[T, C], [Cᵀ, A]] = det T · det (A − Cᵀ T⁻¹ C)` for
   invertible `T` (Mathlib's `Matrix.det_fromBlocks₁₁`), and `det_ldl_product`:
   `det (L D Lᵀ) = ∏ D` when `det L = 1`.  Together they give
   `log|H| = Σ log D_u + log|Q|` once the tree block has such a factorization.
2. `eliminate_support`: one outer-product elimination step changes only the
   entries `(i, j)` with `H i p ≠ 0` and `H p j ≠ 0`; `eliminate_no_fill`: a
   pivot whose neighbour set is a clique of a pattern containing the support
   creates no entry outside that pattern.
3. `comparable_of_support`: for a strictly nested incidence (the ancestors of
   every node form a chain) the tree block `Σ_ℓ w_ℓ [anc u ℓ][anc v ℓ] + λ_u δ_uv`
   is nonzero only for comparable nodes; `ancestors_pairwise_comparable`: the
   ancestors of a node are pairwise comparable; `nested_leaf_pivot_no_fill`: in
   the bordered matrix, eliminating a node whose strict descendants are already
   eliminated creates no fill.  Applied at every step of a descendants-first
   ordering, this is the perfect-elimination-ordering statement.
4. `star_pivot`: the scalar identity `λ_p + Σ_c (w_c − w_c²/(w_c+λ_c)) = λ_p +
   Σ_c w_c λ_c/(w_c+λ_c)`, which is the two forms of the parent pivot `D_p` once
   item 7 has identified the eliminated mass of child `c` as `ω_c²/(ω_c+λ_c)`
   (there is no matrix or elimination step in this statement itself), and
   `star_pivot_ge`: the right-hand side is at least `λ_p` when `w_c ≥ 0` and
   `λ_c > 0`.
5. `weighted_scatter`: `Σ_i w_i (x_i − m)(x_i − m)ᵀ = Σ_i w_i x_i x_iᵀ − W m mᵀ`
   when `W m = Σ_i w_i x_i`; `pivot_mass_split`: `ω²/(ω+λ) = ω − ωλ/(ω+λ)`; and
   `star_psd_eq_subtraction`: at one parent with its children, the PSD-sum
   contribution equals the subtraction-form contribution.
6. `trace_selector_frobenius`: `tr(G E_I G E_J) = Σ_{i∈I} Σ_{j∈J} (G i j)²` for
   symmetric `G` and coordinate selectors `E_I`, `E_J`.
7. `chain_ldl`: the recursion's multipliers `L_{a,u} = σ_u` (`a` a strict
   ancestor of `u`) and pivots `D_u = ω_u + λ_u` satisfy `L diag(D) Lᵀ = T` for
   the tree block `T` of item 3, given the local recursion equations
   `σ_u = ω_u / D_u`, `s_u = ω_u − ω_u σ_u` (`= ω_u λ_u / D_u`), `ω_u = w_u +
   Σ_{parent c = u} s_c` and a forest `anc` (reflexive, antisymmetric,
   transitive, strictly nested, generated by `parent`).  The load-bearing
   lemma is `subtree_telescope`, `Σ_{v ⪯ u} ω_v = Σ_{v ⪯ u} w_v + Σ_{v ≺ u} s_v`,
   which is the constant-ancestor-column invariant of the elimination: after a
   node's descendants are eliminated, its column on its ancestors is the
   constant `ω_u`.  `chainL_det`: `det L = 1` given a depth function that
   strictly increases from ancestors to descendants (`L` is block triangular
   with identity diagonal blocks), and `chain_det`: `det T = ∏_u D_u`.  With
   item 1 this is `log|H| = Σ_u log D_u + log|Q|` for the bordered matrix.

Not proved: floating-point behaviour, complexity, convergence, positive
definiteness, that the float64 code computes the `ω, s, σ, D` of item 7 (its
hypotheses are the exact recursion), the telescoping of item 5 over an
arbitrary tree (only one star is assembled), and the iterated multi-step
no-fill statement (item 3 is the one-step inductive kernel).

Repository base: 36b330a0 (branch claude/superglm-exotic-types-17abdd).
Date: 2026-09-27.
-/

open Matrix
open scoped BigOperators

namespace SuperGLM.Nested

/-! ### 1. Block determinant identities -/

section Determinant

variable {m n : Type*} [Fintype m] [Fintype n] [DecidableEq m] [DecidableEq n]

/-- Block Schur determinant identity for a symmetric bordered matrix. -/
theorem det_bordered_schur (T : Matrix m m ℝ) (C : Matrix m n ℝ) (A : Matrix n n ℝ)
    [Invertible T] :
    (Matrix.fromBlocks T C Cᵀ A).det = T.det * (A - Cᵀ * ⅟T * C).det :=
  Matrix.det_fromBlocks₁₁ T C Cᵀ A

/-- A unit-determinant congruence of a diagonal has the product of the pivots as determinant. -/
theorem det_ldl_product (L : Matrix m m ℝ) (d : m → ℝ) (hL : L.det = 1) :
    (L * Matrix.diagonal d * Lᵀ).det = ∏ i, d i := by
  rw [Matrix.det_mul, Matrix.det_mul, Matrix.det_transpose, hL, Matrix.det_diagonal]
  ring

end Determinant

/-! ### 2. One elimination step and its support -/

section Elimination

variable {ι : Type*}

/-- Outer-product elimination of pivot `p`; the row and column of `p` are zeroed. -/
noncomputable def eliminate (H : Matrix ι ι ℝ) (p : ι) : Matrix ι ι ℝ :=
  fun i j => H i j - H i p * H p j / H p p

theorem eliminate_support (H : Matrix ι ι ℝ) (p i j : ι) (h : H i p = 0 ∨ H p j = 0) :
    eliminate H p i j = H i j := by
  rcases h with h | h <;> simp [eliminate, h]

/-- No fill: if the neighbours of the pivot form a clique of a pattern `P` that
contains the support, the eliminated matrix is still supported on `P`. -/
theorem eliminate_no_fill (H : Matrix ι ι ℝ) (P : ι → ι → Prop) (p : ι)
    (hsupp : ∀ i j, H i j ≠ 0 → P i j)
    (hclique : ∀ i j, H i p ≠ 0 → H p j ≠ 0 → P i j) :
    ∀ i j, eliminate H p i j ≠ 0 → P i j := by
  intro i j hne
  by_cases hi : H i p = 0
  · exact hsupp i j (by rwa [eliminate_support H p i j (Or.inl hi)] at hne)
  by_cases hj : H p j = 0
  · exact hsupp i j (by rwa [eliminate_support H p i j (Or.inr hj)] at hne)
  exact hclique i j hi hj

end Elimination

/-! ### 3. Strictly nested incidence -/

section Nesting

variable {Node : Type*}

/-- The ancestors (or self) of every node form a chain: strict nesting. -/
def Chain (anc : Node → Node → Prop) : Prop :=
  ∀ ℓ u v, anc u ℓ → anc v ℓ → anc u v ∨ anc v u

/-- Tree block of the penalized Hessian: rows are aggregated at nodes with
weights `w` (zero at internal nodes), `anc u ℓ` reads "u is an ancestor of, or
equal to, ℓ", and `lam` is the ridge penalty. -/
noncomputable def treeBlock [Fintype Node] [DecidableEq Node]
    (anc : Node → Node → Prop) [DecidableRel anc]
    (w lam : Node → ℝ) : Matrix Node Node ℝ :=
  fun u v =>
    (∑ ℓ, w ℓ * (if anc u ℓ then (1 : ℝ) else 0) * (if anc v ℓ then (1 : ℝ) else 0)) +
      (if u = v then lam u else 0)

/-- The tree block is supported on comparable pairs. -/
theorem comparable_of_support [Fintype Node] [DecidableEq Node]
    (anc : Node → Node → Prop) [DecidableRel anc]
    (hchain : Chain anc) (w lam : Node → ℝ) (u v : Node)
    (hne : treeBlock anc w lam u v ≠ 0) : u = v ∨ anc u v ∨ anc v u := by
  by_contra hcon
  have h1 : u ≠ v := fun h => hcon (Or.inl h)
  have h2 : ¬ anc u v := fun h => hcon (Or.inr (Or.inl h))
  have h3 : ¬ anc v u := fun h => hcon (Or.inr (Or.inr h))
  apply hne
  unfold treeBlock
  rw [if_neg h1, add_zero]
  apply Finset.sum_eq_zero
  intro ℓ _
  by_cases hu : anc u ℓ
  · by_cases hv : anc v ℓ
    · exact absurd (hchain ℓ u v hu hv) (not_or.mpr ⟨h2, h3⟩)
    · simp [hv]
  · simp [hu]

/-- The ancestors of a node are pairwise comparable: a clique of the pattern. -/
theorem ancestors_pairwise_comparable (anc : Node → Node → Prop) (hchain : Chain anc)
    (u a b : Node) (ha : anc a u) (hb : anc b u) : anc a b ∨ anc b a :=
  hchain u a b ha hb

/-- The chordal pattern of a nested chain beside a dense border. -/
def borderedPattern {β : Type*} (anc : Node → Node → Prop) :
    Node ⊕ β → Node ⊕ β → Prop
  | Sum.inl u, Sum.inl v => u = v ∨ anc u v ∨ anc v u
  | _, _ => True

/-- Eliminating a node whose strict descendants are already eliminated (their
rows and columns are zero) keeps the bordered matrix on the chordal pattern:
its remaining neighbours are itself, its ancestors and the border. -/
theorem nested_leaf_pivot_no_fill {β : Type*} (anc : Node → Node → Prop)
    (hchain : Chain anc) (Hcur : Matrix (Node ⊕ β) (Node ⊕ β) ℝ) (u : Node)
    (hsupp : ∀ i j, Hcur i j ≠ 0 → borderedPattern anc i j)
    (hdesc : ∀ v, anc u v → v ≠ u →
      ∀ x, Hcur (Sum.inl v) x = 0 ∧ Hcur x (Sum.inl v) = 0) :
    ∀ i j, eliminate Hcur (Sum.inl u) i j ≠ 0 → borderedPattern anc i j := by
  refine eliminate_no_fill Hcur (borderedPattern anc) (Sum.inl u) hsupp ?_
  intro i j hi hj
  have key : ∀ a : Node,
      Hcur (Sum.inl a) (Sum.inl u) ≠ 0 ∨ Hcur (Sum.inl u) (Sum.inl a) ≠ 0 →
        a = u ∨ anc a u := by
    intro a ha
    have hcases : a = u ∨ anc a u ∨ anc u a := by
      rcases ha with ha | ha
      · exact hsupp _ _ ha
      · rcases hsupp _ _ ha with h | h | h
        · exact Or.inl h.symm
        · exact Or.inr (Or.inr h)
        · exact Or.inr (Or.inl h)
    rcases hcases with h | h | h
    · exact Or.inl h
    · exact Or.inr h
    · by_cases hau : a = u
      · exact Or.inl hau
      · exfalso
        rcases ha with ha | ha
        · exact ha (hdesc a h hau _).1
        · exact ha (hdesc a h hau _).2
  cases i with
  | inr _ => simp [borderedPattern]
  | inl a =>
    cases j with
    | inr _ => simp [borderedPattern]
    | inl b =>
      have ha := key a (Or.inl hi)
      have hb := key b (Or.inr hj)
      simp only [borderedPattern]
      rcases ha with ha | ha <;> rcases hb with hb | hb
      · exact Or.inl (ha.trans hb.symm)
      · exact Or.inr (Or.inr (by rw [ha]; exact hb))
      · exact Or.inr (Or.inl (by rw [hb]; exact ha))
      · exact Or.inr (hchain u a b ha hb)

end Nesting

/-! ### 4. The scalar star identity behind the pivot recursion -/

section Star

variable {ι : Type*}

/-- The parent pivot after eliminating its children: `w_c` is the child's
accumulated weight `ω_c` and `w_c + λ_c` its pivot. -/
theorem star_pivot (s : Finset ι) (w lam : ι → ℝ) (lamp : ℝ)
    (hpos : ∀ c ∈ s, w c + lam c ≠ 0) :
    lamp + ∑ c ∈ s, (w c - w c ^ 2 / (w c + lam c)) =
      lamp + ∑ c ∈ s, w c * lam c / (w c + lam c) := by
  congr 1
  apply Finset.sum_congr rfl
  intro c hc
  have h := hpos c hc
  field_simp
  ring

/-- Non-negative weights and positive penalties keep every pivot at least `λ_p`. -/
theorem star_pivot_ge (s : Finset ι) (w lam : ι → ℝ) (lamp : ℝ)
    (hw : ∀ c ∈ s, 0 ≤ w c) (hl : ∀ c ∈ s, 0 < lam c) :
    lamp ≤ lamp + ∑ c ∈ s, w c * lam c / (w c + lam c) := by
  have : 0 ≤ ∑ c ∈ s, w c * lam c / (w c + lam c) := by
    apply Finset.sum_nonneg
    intro c hc
    exact div_nonneg (mul_nonneg (hw c hc) (le_of_lt (hl c hc)))
      (le_of_lt (add_pos_of_nonneg_of_pos (hw c hc) (hl c hc)))
  linarith

end Star

/-! ### 5. PSD-sum form of the border Schur complement -/

section Scatter

variable {ι n : Type*} [Fintype ι]

/-- Weighted scatter about a weighted mean: the within-leaf and between-child
terms of the PSD-sum form are both instances. -/
theorem weighted_scatter (w : ι → ℝ) (x : ι → n → ℝ) (m : n → ℝ)
    (hm : ∀ j, (∑ i, w i) * m j = ∑ i, w i * x i j) :
    ∑ i, w i • Matrix.vecMulVec (x i - m) (x i - m) =
      ∑ i, w i • Matrix.vecMulVec (x i) (x i) - (∑ i, w i) • Matrix.vecMulVec m m := by
  ext j l
  simp only [Matrix.sum_apply, Matrix.sub_apply, Matrix.smul_apply, Matrix.vecMulVec_apply,
    Pi.sub_apply, smul_eq_mul]
  have expand : ∀ i, w i * ((x i j - m j) * (x i l - m l)) =
      w i * (x i j * x i l) - m l * (w i * x i j) - m j * (w i * x i l) + (m j * m l) * w i := by
    intro i
    ring
  simp only [expand, Finset.sum_add_distrib, Finset.sum_sub_distrib, ← Finset.mul_sum]
  have hj := hm j
  have hl := hm l
  linear_combination (m l) * hj + (m j) * hl

/-- The eliminated mass of one pivot: `ω²/(ω+λ) = ω − ωλ/(ω+λ)`. -/
theorem pivot_mass_split (omega lam : ℝ) (h : omega + lam ≠ 0) :
    omega ^ 2 / (omega + lam) = omega - omega * lam / (omega + lam) := by
  field_simp
  ring

/-- One star of the tree: children `c` with accumulated weights `w c`, shrunk
weights `s c = w c λ_c/(w c+λ_c)` and means `m c`; the parent has weight
`Σ s c`, mean `mp` with `(Σ s c) mp = Σ s c • m c`, and shrunk weight `sp`.
The PSD-sum contribution (between-child scatter, root term, minus the child
masses moved into the within-child scatter) equals the subtraction-form
contribution `−Σ_c (w_c²/(w_c+λ_c)) m_c m_cᵀ − (ω_p²/(ω_p+λ_p)) mp mpᵀ`. -/
theorem star_psd_eq_subtraction (w lam : ι → ℝ) (m : ι → n → ℝ) (mp : n → ℝ)
    (lamp : ℝ) (hpos : ∀ c, w c + lam c ≠ 0)
    (hposp : (∑ c, w c * lam c / (w c + lam c)) + lamp ≠ 0)
    (hm : ∀ j, (∑ c, w c * lam c / (w c + lam c)) * mp j =
      ∑ c, w c * lam c / (w c + lam c) * m c j) :
    ∑ c, (w c * lam c / (w c + lam c)) • Matrix.vecMulVec (m c - mp) (m c - mp) +
        ((∑ c, w c * lam c / (w c + lam c)) * lamp /
          ((∑ c, w c * lam c / (w c + lam c)) + lamp)) • Matrix.vecMulVec mp mp -
        ∑ c, w c • Matrix.vecMulVec (m c) (m c) =
      -(∑ c, (w c ^ 2 / (w c + lam c)) • Matrix.vecMulVec (m c) (m c)) -
        ((∑ c, w c * lam c / (w c + lam c)) ^ 2 /
          ((∑ c, w c * lam c / (w c + lam c)) + lamp)) • Matrix.vecMulVec mp mp := by
  rw [weighted_scatter (fun c => w c * lam c / (w c + lam c)) m mp hm]
  ext j l
  simp only [Matrix.sum_apply, Matrix.sub_apply, Matrix.add_apply, Matrix.neg_apply,
    Matrix.smul_apply, Matrix.vecMulVec_apply, smul_eq_mul]
  have hchild : ∀ c, w c ^ 2 / (w c + lam c) * (m c j * m c l) =
      w c * (m c j * m c l) - w c * lam c / (w c + lam c) * (m c j * m c l) := by
    intro c
    rw [pivot_mass_split (w c) (lam c) (hpos c)]
    ring
  have hparent := pivot_mass_split (∑ c, w c * lam c / (w c + lam c)) lamp hposp
  simp only [hchild, Finset.sum_sub_distrib]
  rw [hparent]
  ring

end Scatter

/-! ### 6. Cross traces of coordinate selectors -/

section Selector

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- `tr(G E_I G E_J) = ‖G_{IJ}‖_F²` for symmetric `G`. -/
theorem trace_selector_frobenius (G : Matrix ι ι ℝ) (hG : Gᵀ = G) (I J : Finset ι) :
    Matrix.trace (G * Matrix.diagonal (fun i => if i ∈ I then (1 : ℝ) else 0) * G *
        Matrix.diagonal (fun j => if j ∈ J then (1 : ℝ) else 0)) =
      ∑ i ∈ I, ∑ j ∈ J, G i j ^ 2 := by
  have hsym : ∀ i j, G j i = G i j := fun i j => by
    simpa [Matrix.transpose_apply] using congrFun (congrFun hG i) j
  have h1 : ∀ i, (G * Matrix.diagonal (fun i => if i ∈ I then (1 : ℝ) else 0) * G *
      Matrix.diagonal (fun j => if j ∈ J then (1 : ℝ) else 0)) i i =
      (G * Matrix.diagonal (fun i => if i ∈ I then (1 : ℝ) else 0) * G) i i *
        (if i ∈ J then (1 : ℝ) else 0) := fun i => Matrix.mul_diagonal _ _ _ _
  have h2 : ∀ i, (G * Matrix.diagonal (fun i => if i ∈ I then (1 : ℝ) else 0) * G) i i =
      ∑ k, G i k * (if k ∈ I then (1 : ℝ) else 0) * G k i := fun i => by
    rw [Matrix.mul_apply]
    simp only [Matrix.mul_diagonal]
  simp only [Matrix.trace, Matrix.diag_apply, h1, h2, mul_ite, mul_one, mul_zero, ite_mul,
    zero_mul]
  rw [Finset.sum_ite_mem, Finset.univ_inter]
  conv_rhs => rw [Finset.sum_comm]
  refine Finset.sum_congr rfl ?_
  intro j _
  rw [Finset.sum_ite_mem, Finset.univ_inter]
  refine Finset.sum_congr rfl ?_
  intro i _
  rw [hsym i j]
  ring

end Selector

/-! ### 7. The recursion's factorization `T = L D Lᵀ` -/

section Factorization

variable {Node : Type*} [Fintype Node] [DecidableEq Node]

/-- The multiplier matrix of the recursion: `σ_u` from `u` to every strict ancestor `a`,
`1` on the diagonal, `0` elsewhere. -/
noncomputable def chainL (anc : Node → Node → Prop) [DecidableRel anc] (sigma : Node → ℝ) :
    Matrix Node Node ℝ :=
  fun a u => if a = u then 1 else if anc a u then sigma u else 0

/-- Telescoping over a subtree: with `ω_u = w_u + Σ_{parent c = u} s_c`, the accumulated
weights of a subtree minus the shrunk weights of its strict descendants are its raw weights.
This is the constant-ancestor-column invariant of the elimination. -/
theorem subtree_telescope (anc : Node → Node → Prop) [DecidableRel anc]
    (parent : Node → Option Node) (w omega s : Node → ℝ) (a : Node)
    (hparent : ∀ c, (anc a c ∧ c ≠ a) ↔ ∃ p, parent c = some p ∧ anc a p)
    (homega : ∀ u, omega u = w u + ∑ c ∈ Finset.univ.filter (fun c => parent c = some u), s c) :
    ∑ v ∈ Finset.univ.filter (fun v => anc a v), omega v =
      ∑ v ∈ Finset.univ.filter (fun v => anc a v), w v +
        ∑ c ∈ Finset.univ.filter (fun c => anc a c ∧ c ≠ a), s c := by
  simp only [homega, Finset.sum_add_distrib]
  congr 1
  rw [Finset.sum_filter, Finset.sum_filter]
  have inner : ∀ v, (if anc a v then ∑ c ∈ Finset.univ.filter (fun c => parent c = some v), s c
      else 0) = ∑ c, if anc a v ∧ parent c = some v then s c else 0 := by
    intro v
    rw [Finset.sum_filter]
    by_cases h : anc a v <;> simp [h]
  simp only [inner]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl ?_
  intro c _
  cases hp : parent c with
  | none =>
    have hno : ¬ (anc a c ∧ c ≠ a) := by
      intro h
      obtain ⟨p, hp', _⟩ := (hparent c).1 h
      rw [hp] at hp'
      exact Option.some_ne_none p hp'.symm
    simp [hno]
  | some p =>
    have hiff : (anc a c ∧ c ≠ a) ↔ anc a p := by
      rw [hparent c]
      constructor
      · rintro ⟨p', hp', hap⟩
        rw [hp] at hp'
        rw [Option.some.injEq] at hp'
        rw [hp']
        exact hap
      · intro h
        exact ⟨p, hp, h⟩
    rw [Finset.sum_eq_single p]
    · simp [hiff]
    · intro v _ hv
      simp [Ne.symm hv]
    · intro h
      exact absurd (Finset.mem_univ p) h

/-- Splitting the subtree of `a` into `a` and its strict descendants. -/
theorem sum_subtree_split (anc : Node → Node → Prop) [DecidableRel anc] (a : Node)
    (hrefl : anc a a) (f : Node → ℝ) :
    ∑ v ∈ Finset.univ.filter (fun v => anc a v), f v =
      f a + ∑ v ∈ Finset.univ.filter (fun v => anc a v ∧ v ≠ a), f v := by
  rw [← Finset.add_sum_erase _ _ (by simp [hrefl] : a ∈ Finset.univ.filter (fun v => anc a v))]
  congr 1
  apply Finset.sum_congr
  · ext v
    simp [Finset.mem_erase, Finset.mem_filter, and_comm]
  · intros
    rfl

/-- One row of `L D Lᵀ` against an ancestor-or-self `b` of `a`. -/
theorem chain_ldl_entry (anc : Node → Node → Prop) [DecidableRel anc]
    (parent : Node → Option Node) (w lam omega D sigma s : Node → ℝ)
    (hrefl : ∀ u, anc u u)
    (hanti : ∀ u v, anc u v → anc v u → u = v)
    (htrans : ∀ u v x, anc u v → anc v x → anc u x)
    (hparent : ∀ a c, (anc a c ∧ c ≠ a) ↔ ∃ p, parent c = some p ∧ anc a p)
    (hD : ∀ u, D u = omega u + lam u)
    (hDne : ∀ u, D u ≠ 0)
    (hsigma : ∀ u, sigma u = omega u / D u)
    (hs : ∀ u, s u = omega u - omega u * sigma u)
    (homega : ∀ u, omega u = w u + ∑ c ∈ Finset.univ.filter (fun c => parent c = some u), s c)
    (a b : Node) (hba : anc b a) :
    ∑ u, chainL anc sigma a u * D u * chainL anc sigma b u =
      (if a = b then lam a else 0) + ∑ v ∈ Finset.univ.filter (fun v => anc a v), w v := by
  have hsq : ∀ u, sigma u * D u * sigma u = omega u - s u := by
    intro u
    rw [hs u, hsigma u]
    field_simp [hDne u]
    ring
  have hsd : ∀ u, D u * sigma u = omega u := by
    intro u
    rw [hsigma u]
    field_simp [hDne u]
  -- split off u = a
  rw [← Finset.add_sum_erase _ _ (Finset.mem_univ a)]
  have hrest : ∑ u ∈ Finset.univ.erase a, chainL anc sigma a u * D u * chainL anc sigma b u =
      ∑ u ∈ Finset.univ.filter (fun u => anc a u ∧ u ≠ a), (omega u - s u) := by
    have hset : Finset.univ.filter (fun u => anc a u ∧ u ≠ a) =
        (Finset.univ.erase a).filter (fun u => anc a u) := by
      ext u
      simp [Finset.mem_filter, Finset.mem_erase, and_comm]
    rw [hset, Finset.sum_filter]
    refine Finset.sum_congr rfl ?_
    intro u hu
    have hua : u ≠ a := Finset.ne_of_mem_erase hu
    by_cases hau : anc a u
    · have hbu : anc b u := htrans b a u hba hau
      have hbu' : b ≠ u := by
        intro hb
        subst hb
        exact hua (hanti a b hau hba).symm
      simp only [chainL, if_neg (Ne.symm hua), if_pos hau, if_neg hbu', if_pos hbu]
      exact hsq u
    · simp [chainL, Ne.symm hua, hau]
  rw [hrest]
  have hself : chainL anc sigma a a * D a * chainL anc sigma b a =
      (if a = b then lam a else 0) + omega a := by
    by_cases hab : a = b
    · subst hab
      simp [chainL, hD a, add_comm]
    · simp only [chainL, ite_true, if_neg (Ne.symm hab), if_pos hba, if_neg hab, one_mul, zero_add]
      exact hsd a
  rw [hself, sum_subtree_split anc a (hrefl a) w, add_assoc]
  congr 1
  have htel := subtree_telescope anc parent w omega s a (hparent a) homega
  rw [sum_subtree_split anc a (hrefl a) omega, sum_subtree_split anc a (hrefl a) w] at htel
  rw [Finset.sum_sub_distrib]
  linarith

/-- The recursion's multipliers and pivots factor the tree block: `T = L D Lᵀ`.  The
hypotheses are the recursion itself (`D = ω + λ`, `σ = ω / D`, `s = ω − ω σ`,
`ω_u = w_u + Σ_{parent c = u} s_c`) and the forest structure of `anc` (reflexive,
antisymmetric, transitive, strictly nested, generated by `parent`). -/
theorem chain_ldl (anc : Node → Node → Prop) [DecidableRel anc] (parent : Node → Option Node)
    (w lam omega D sigma s : Node → ℝ)
    (hrefl : ∀ u, anc u u)
    (hanti : ∀ u v, anc u v → anc v u → u = v)
    (htrans : ∀ u v x, anc u v → anc v x → anc u x)
    (hchain : Chain anc)
    (hparent : ∀ a c, (anc a c ∧ c ≠ a) ↔ ∃ p, parent c = some p ∧ anc a p)
    (hD : ∀ u, D u = omega u + lam u)
    (hDne : ∀ u, D u ≠ 0)
    (hsigma : ∀ u, sigma u = omega u / D u)
    (hs : ∀ u, s u = omega u - omega u * sigma u)
    (homega : ∀ u, omega u = w u + ∑ c ∈ Finset.univ.filter (fun c => parent c = some u), s c) :
    chainL anc sigma * Matrix.diagonal D * (chainL anc sigma)ᵀ = treeBlock anc w lam := by
  ext a b
  have entry : (chainL anc sigma * Matrix.diagonal D * (chainL anc sigma)ᵀ) a b =
      ∑ u, chainL anc sigma a u * D u * chainL anc sigma b u := by
    rw [Matrix.mul_apply]
    simp only [Matrix.mul_diagonal, Matrix.transpose_apply]
  rw [entry]
  have key := chain_ldl_entry anc parent w lam omega D sigma s hrefl hanti htrans hparent hD hDne
    hsigma hs homega
  have tree : ∀ a b, anc b a → treeBlock anc w lam a b =
      (if a = b then lam a else 0) + ∑ v ∈ Finset.univ.filter (fun v => anc a v), w v := by
    intro a b hba
    simp only [treeBlock]
    rw [add_comm]
    congr 1
    rw [Finset.sum_filter]
    refine Finset.sum_congr rfl ?_
    intro ℓ _
    by_cases h : anc a ℓ
    · simp [h, htrans b a ℓ hba h]
    · simp [h]
  by_cases hab : anc b a
  · rw [key a b hab, tree a b hab]
  have hne : a ≠ b := fun h => hab (h ▸ hrefl a)
  by_cases hba : anc a b
  · have hsym : ∑ u, chainL anc sigma a u * D u * chainL anc sigma b u =
        ∑ u, chainL anc sigma b u * D u * chainL anc sigma a u := by
      refine Finset.sum_congr rfl ?_
      intro u _
      ring
    have tsym : treeBlock anc w lam a b = treeBlock anc w lam b a := by
      simp only [treeBlock]
      rw [if_neg hne, if_neg (Ne.symm hne)]
      congr 1
      refine Finset.sum_congr rfl ?_
      intro ℓ _
      ring
    rw [hsym, key b a hba, tsym, tree b a hba]
  · have hzero : treeBlock anc w lam a b = 0 := by
      by_contra h
      rcases comparable_of_support anc hchain w lam a b h with h | h | h
      · exact hne h
      · exact hba h
      · exact hab h
    rw [hzero]
    apply Finset.sum_eq_zero
    intro u _
    by_cases hau : anc a u
    · have hbu : ¬ anc b u := fun hbu => (not_or.mpr ⟨hba, hab⟩) (hchain u a b hau hbu)
      have hbu' : b ≠ u := fun h => hbu (h ▸ hrefl b)
      simp [chainL, hbu, hbu']
    · have hau' : a ≠ u := fun h => hau (h ▸ hrefl a)
      simp [chainL, hau, hau']

/-- With a depth function that strictly increases from ancestors to descendants, `L` is
block triangular with identity diagonal blocks, so its determinant is `1`. -/
theorem chainL_det (anc : Node → Node → Prop) [DecidableRel anc] (sigma : Node → ℝ)
    (depth : Node → ℕ) (hdepth : ∀ a u, anc a u → a ≠ u → depth a < depth u) :
    (chainL anc sigma).det = 1 := by
  have htri : (chainL anc sigma).BlockTriangular depth := by
    intro i j hij
    simp only [chainL]
    by_cases hij' : i = j
    · subst hij'
      exact absurd hij (lt_irrefl _)
    · rw [if_neg hij']
      by_cases h : anc i j
      · exact absurd (hdepth i j h hij') (not_lt.mpr (le_of_lt hij))
      · rw [if_neg h]
  rw [htri.det]
  apply Finset.prod_eq_one
  intro d _
  have hblock : (chainL anc sigma).toSquareBlock depth d = 1 := by
    ext ⟨i, hi⟩ ⟨j, hj⟩
    simp only [Matrix.toSquareBlock_def, Matrix.of_apply, chainL, Matrix.one_apply,
      Subtype.mk.injEq]
    by_cases hij : i = j
    · simp [hij]
    · rw [if_neg hij, if_neg hij]
      by_cases h : anc i j
      · exact absurd (hdepth i j h hij) (by rw [hi, hj]; exact lt_irrefl d)
      · rw [if_neg h]
  rw [hblock, Matrix.det_one]

/-- The tree block's determinant is the product of the recursion's pivots. -/
theorem chain_det (anc : Node → Node → Prop) [DecidableRel anc] (parent : Node → Option Node)
    (w lam omega D sigma s : Node → ℝ) (depth : Node → ℕ)
    (hdepth : ∀ a u, anc a u → a ≠ u → depth a < depth u)
    (hrefl : ∀ u, anc u u)
    (hanti : ∀ u v, anc u v → anc v u → u = v)
    (htrans : ∀ u v x, anc u v → anc v x → anc u x)
    (hchain : Chain anc)
    (hparent : ∀ a c, (anc a c ∧ c ≠ a) ↔ ∃ p, parent c = some p ∧ anc a p)
    (hD : ∀ u, D u = omega u + lam u)
    (hDne : ∀ u, D u ≠ 0)
    (hsigma : ∀ u, sigma u = omega u / D u)
    (hs : ∀ u, s u = omega u - omega u * sigma u)
    (homega : ∀ u, omega u = w u + ∑ c ∈ Finset.univ.filter (fun c => parent c = some u), s c) :
    (treeBlock anc w lam).det = ∏ u, D u := by
  rw [← chain_ldl anc parent w lam omega D sigma s hrefl hanti htrans hchain hparent hD hDne
    hsigma hs homega]
  exact det_ldl_product _ _ (chainL_det anc sigma depth hdepth)

end Factorization

end SuperGLM.Nested

#print axioms SuperGLM.Nested.det_bordered_schur
#print axioms SuperGLM.Nested.det_ldl_product
#print axioms SuperGLM.Nested.eliminate_support
#print axioms SuperGLM.Nested.eliminate_no_fill
#print axioms SuperGLM.Nested.comparable_of_support
#print axioms SuperGLM.Nested.ancestors_pairwise_comparable
#print axioms SuperGLM.Nested.nested_leaf_pivot_no_fill
#print axioms SuperGLM.Nested.star_pivot
#print axioms SuperGLM.Nested.star_pivot_ge
#print axioms SuperGLM.Nested.weighted_scatter
#print axioms SuperGLM.Nested.pivot_mass_split
#print axioms SuperGLM.Nested.star_psd_eq_subtraction
#print axioms SuperGLM.Nested.trace_selector_frobenius
#print axioms SuperGLM.Nested.subtree_telescope
#print axioms SuperGLM.Nested.chain_ldl
#print axioms SuperGLM.Nested.chainL_det
#print axioms SuperGLM.Nested.chain_det
