"""Every public name in ``superglm.__all__`` has an entry in the API reference.

The reference is generated by autosummary from the ``.. autosummary::``
directives inside the ``{eval-rst}`` fences under ``docs/api``. A new
export without an entry fails here, not on a reader's screen.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

import superglm

DOCS_API = Path(__file__).resolve().parents[2] / "docs" / "api"
AUTOSUMMARY_BLOCK = re.compile(r"```\{eval-rst\}\s*\n\s*\.\.\s+autosummary::(.*?)```", re.S)


def documented_names() -> set[str]:
    names: set[str] = set()
    for page in DOCS_API.glob("*.md"):
        for block in AUTOSUMMARY_BLOCK.findall(page.read_text(encoding="utf-8")):
            for raw in block.splitlines():
                line = raw.strip().lstrip("~")
                if line and not line.startswith(":"):
                    names.add(line.removeprefix("superglm."))
    return names


def test_every_public_name_has_a_reference_entry() -> None:
    missing = sorted(set(superglm.__all__) - documented_names())
    assert missing == [], f"public names without an API reference entry: {missing}"


MEMBER_PAGES = {
    "SuperGLM": DOCS_API / "model.md",
    "SuperLSS": DOCS_API / "distributional.md",
}


def listed_members(page: Path, cls_name: str) -> list[str]:
    prefix = f"superglm.{cls_name}."
    members: list[str] = []
    for block in AUTOSUMMARY_BLOCK.findall(page.read_text(encoding="utf-8")):
        for raw in block.splitlines():
            line = raw.strip().lstrip("~")
            if line.startswith(prefix):
                members.append(line.removeprefix(prefix))
    return members


@pytest.mark.parametrize("cls_name", sorted(MEMBER_PAGES))
def test_every_public_member_is_grouped_exactly_once(cls_name: str) -> None:
    """The two big classes list every public member once, under a task heading."""
    cls = getattr(superglm, cls_name)
    public = {name for name in dir(cls) if not name.startswith("_")}
    listed = listed_members(MEMBER_PAGES[cls_name], cls_name)
    duplicates = sorted({m for m in listed if listed.count(m) > 1})
    missing = sorted(public - set(listed))
    unknown = sorted(set(listed) - public)
    assert duplicates == [], f"{cls_name} members listed twice: {duplicates}"
    assert missing == [], f"{cls_name} members with no grouped entry: {missing}"
    assert unknown == [], f"{cls_name} entries that are not public members: {unknown}"
